apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec: # for deployment
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template: # blueprint for pod
    metadata:
      labels:
        app: nginx
    spec: # for pods
      containers:
        - name: nginx
          image: nginx:1.16
          ports:
            - containerPort: 8080
